#
# To create a fresh docker image run this command
# docker build -t docker.blinkboxmusic.com/blinkboxmusic/blah .
# # Dont forget the dot at the end !
#
# To push the image to the we7 registry....
# docker push docker.blinkboxmusic.com/blinkboxmusic/blah
#
# YOU DO NOT HAVE TO DO THE ABOVE UNLESS THE registry image needs updating
#
FROM docker.blinkboxmusic.com/blinkboxmusic/debian_java8
MAINTAINER Gus Robinson  <gus@blinkbox.com>

#RUN apt-get install -qqy curl
#RUN curl http://jenkins.we7.local/repository/dists/qa/pubkey.gpg | apt-key add -
#ADD ./files/sources.list /etc/apt/sources.list

RUN apt-get update

RUN mkdir -p /var/tmp/bbm-radio-site && \
    chmod 1777 /var/tmp && \
    chmod 1777 /var/tmp/bbm-radio-site

COPY artifacts/website.deb         /website.deb
COPY artifacts/website-assets.deb  /website-assets.deb
COPY artifacts/website-assets2.deb /website-assets2.deb
COPY artifacts/cucumberTests.deb   /cucumberTests.deb

RUN dpkg -i *.deb || apt-get -f -y -q install

RUN mkdir /var/lib/bbm-radio-site/logs && \
    chown bbm-radio-site /var/lib/bbm-radio-site/logs

RUN mkdir /var/lib/bbm-radio-site/webapps && \
    chown bbm-radio-site /var/lib/bbm-radio-site/webapps

#COPY artifacts/tomcat_keystore /usr/share/bbm-radio-site/tomcat_keystore

COPY files/radio-site-log4j.xml /etc/bbm/radio-site-log4j.xml
COPY files/radio-site-tomcat.yml /etc/bbm/radio-site-tomcat.yml

COPY files/local.props /etc/we7/local.props

COPY files/start-radio-site.sh /start-radio-site.sh
RUN chmod +x /start-radio-site.sh


