#!/bin/bash

IMAGE=debian_java8
CONTAINER=debian_java8_bash

case $1 in

start)
  docker run -i --rm --name="${CONTAINER}" -t docker.blinkboxmusic.com/blinkboxmusic/${IMAGE} bash
  ;;
stop)
  docker ps --no-trunc | grep "${CONTAINER}" | awk '{print $1}' | xargs -L 1 -r docker stop
  docker ps -a --no-trunc | grep "${CONTAINER}" | awk '{print $1}' | xargs -L 1 -r docker rm
  ;;
create)
  docker build -t docker.blinkboxmusic.com/blinkboxmusic/${IMAGE} .
  ;;
push)
  docker push docker.blinkboxmusic.com/blinkboxmusic/${IMAGE}
  ;;
*)
  echo "Usage:  ./dock <option>"
  echo "start     - start the container running with a BASH prompt"
  echo "stop      - stop and remove a running container"
  echo "create    - create a docker container image"
  echo "push      - push a docker container image to the registry THINK CAREFULLY!!"
  ;;
esac

exit 0



if [[ $1 == "CREATE" ]] ; then                      
  docker build -t docker.blinkboxmusic.com/blinkboxmusic/${IMAGE} .
fi

if [[ $1 == "PUSH" ]] ; then                      
  docker push docker.blinkboxmusic.com/blinkboxmusic/${IMAGE}
fi

