VAGRANTFILE_API_VERSION = '2'
ENV['VAGRANT_DEFAULT_PROVIDER']='docker'


IMAGE_NAME='debian_java8'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider 'docker' do |d|
    d.image = 'debian_java8'
    d.build_args = "--rm -t #{IMAGE_NAME}".split(' ')
#    d.name = 'test3'
    d.remains_running = false
  end
end


